### ISSUE TITLE
STIMPACK both in buff_id and upgrade_id 

### ISSUE THREAD

**Issue by tweakimp** [Dentosal/python-sc2#104]
The variable `STIMPACK` is both in `buff_id` and `upgrade_id`. That means in `sc2.constants` one of them will be overwritten.

**Comment by BurnySc2** [comment]
This is only true if you do 
```python
from sc2.constants import *
```

You can avoid it by doing:
```python
from sc2.ids.unit_typeid import UnitTypeId
from sc2.ids.ability_id import AbilityId
from sc2.ids.buff_id import BuffId
from sc2.ids.upgrade_id import UpgradeId
from sc2.ids.effect_id import EffectId
```
This is probably the better choice because VScode and pycharm both mark the enums red if you dont have a `UnitTypeId.` in front of the name, unless you disabled that warning.

Also, see https://github.com/Dentosal/python-sc2/issues/58 and https://github.com/Dentosal/python-sc2/issues/55

Sidenote: 
There isn't anything we can do since these are the names directly from the SC2 API.

**Comment by tweakimp** [comment]
Ah yeah you are right. Is is done in many examples like the mass reaper one, i thought it was supposed to be that way.
