### ISSUE TITLE
Issue with pixel_map.py

### ISSUE THREAD

**Issue by danielvschoor** [Dentosal/python-sc2#266]
After the update on 25/04/2019, I am receiving the following error on all the bots I have created which have worked previously:

> File "%APPDATA%\Roaming\Python\Python37\site-packages\sc2\pixel_map.py", line 10, in __init__
> assert self.bits_per_pixel % 8 == 0, "Unsupported pixel density"

It seems like self.bits_per_pixel is equal to 1.

**Comment by BurnySc2** [comment]
Yeah with the new SC2 client version 4.8.5, new things were added to the API and some things were broken without backwards compatibility.
Most things have been fixed on the develop branch of this library / repository.

You can install it with command the
`pip install --upgrade --force-reinstall 
https://github.com/Dentosal/python-sc2/archive/develop.zip`
or instead of `pip` you can go into the python folder and use `python -m pip` instead, if it does not work for you.

**Comment by qq309381** [comment]
good
