### ISSUE TITLE
Get game time or game frame

### ISSUE THREAD

**Issue by BurnySc2** [Dentosal/python-sc2#29]
Is it possible to get the in game time in any reliable way?

Using iteration doesn't seem to be reliable as a source for time.
When using parameter realtime=True 300 iterations mean 10 seconds in game time (in step event: print(iteration) ), while using realtime=False I end up at 110 seconds with the same amount of iterations.

This stat would be very useful when microing (stutter stepping especially) or basing build orders on time (e.g. build engineering bay @ 3:00).

**Comment by Dentosal** [comment]
Yep, iteration is not reliable, as it's just increased once per call into the `on_step` method.  In realtime mode, it's not reliable way to count time, but when stepping, it's always exactly `game_tick_count/8`. I'll look into this.

**Comment by Dentosal** [comment]
Now available as `self.state.game_loop` (version `0.6.2`) This is not the game time in seconds, however, because must be it's adjusted by the fact that the game is running in `faster` speed (just like the sc2 ladder), so a realtime second takes 72.5% of the time. Also, the timer is expressed in 1/10 seconds. So, if `game_loop` is 440, then the game time in clock is `440*0.725*0.1` = 31.9s.

**Comment by Archiatrus** [comment]
The value is slightly off. `faster` means a 1.4 times speedup (or 71.4...%). This means 22.4 loops per second. So the exact time can be calculated via
`game_time = game_loop/(1.4*16) = game_loop/22.4`

For reference: [s2client-proto documentation](https://github.com/Blizzard/s2client-proto/blob/master/docs/protocol.md#game-speed).

**Comment by Dentosal** [comment]
Reopening as bug/enhancement. I'm fixing this for the next version.

**Comment by BurnySc2** [comment]
I added a game time property to the `bot_ai.py` file now, accessable via `self.time` https://github.com/Dentosal/python-sc2/commit/0d88103e908e76eab830bb2dffc7c34a474de89e
