### ISSUE TITLE
Position.towards_random_angle seems to orient incorrectly by default

### ISSUE THREAD

**Issue by hsalokor** [Dentosal/python-sc2#30]
We tested `Position.towards_random_angle` for positioning buildings, and it seems to work quite unintuitively by default.

For example, `cc.position.towards_random_angle(self.game_info.map_center, distance=7)` seemed to position buildings behind the mineral deposits on Abyssal Reef LE.

Flipping the direction, `self.game_info.map_center.towards_random_angle(cc.position, distance=7)` then put the buildings (obviously) to middle of the map.

Is the default angle handling off by a PI?

**Comment by Dentosal** [comment]
Fixed in b441761470ebe81f8f27eec29737358a8382354b, published as version 0.7.0 of `sc2` package:

Method renamed to `towards_with_random_angle`, arguments `distance` and `max_difference` flipped to reflect `Pointlike.towards`. The next commit (2f3c4f9b2563b034fc4ef703a6cfae4a0055435f) also adds some unit tests for these.
