### ISSUE TITLE
Want to figure out how many workers on a mineral patch

### ISSUE THREAD

**Issue by jkottas** [Dentosal/python-sc2#71]
Properties assigned_harvesters and ideal_harvesters don't work on mineral patches like they do on geysers. Possibly this isn't coming through the SC2 client protocol?
```
nearby_minerals = self.state.mineral_field.closer_than(self.DISTANCE_FROM_MINERALS_TO_BASE, base)
for mineral in nearby_minerals:
	print("mineral patch " + str(mineral.position) + " has " + str(mineral.assigned_harvesters) + " harvesters, needs " + str(mineral.ideal_harvesters) + "!") # always 0 and 0
```

**Comment by mjschuetze102** [comment]
The reason is that mineral fields don't count the harvesters. The command center/ nexus/ hatchery keep track (the number above your base). There should be roughly 2 harvesters per mineral field, which is why the number is 12/16 (12 being your total harvesters and 16 being 2x the number of mineral fields (8)) at the start. If you did base.assigned_harvesters, it would only return the number of workers on the mineral fields, it does not include the geyser worker count.

If you are trying to optimize harvesting minerals, I would suggest not. The game provides a decent algorithm for sending workers to a mineral patch. Any changes to it would probably just slow your bot down rather than provide any advantage to harvesting minerals.

**Comment by jkottas** [comment]
That makes sense. I was trying to fix that annoying problem where you've got the right number of workers total (16) but half the patches have 1 worker and the other half have 3. Any idea how the client is figuring out the number of workers per patch? The number displayed when you select a mineral field, that is.

**Comment by mjschuetze102** [comment]
I don't believe we have access to that number on the mineral field. If we do, I don't know how we get it. 

As for the annoying problem: Two workers per patch is ideal, but I believe there is a moment in time when both workers will be at the mineral patch. Since both of them can't harvest at the same time, the other one leaves to a patch not currently being harvested. Then when the worker that was returning to that field shows up, it moves on to a new field. Unfortunately, this algorithm is built into the game itself

**Comment by jkottas** [comment]
Ok, cool. Thanks for replying!
